import { StyleSheet } from "@react-pdf/renderer";

export const invoicePdfStyles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#1e293b",
    backgroundColor: "#ffffff",
  },
  headerBand: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: "#16324F",
    marginBottom: 18,
  },
  brandContainer: {
    flexDirection: "column",
    width: "60%",
  },
  brandName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#16324F",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  brandTagline: {
    fontSize: 8.5,
    fontFamily: "Helvetica-Oblique",
    color: "#167C80",
    marginBottom: 4,
  },
  brandAddress: {
    fontSize: 8,
    color: "#64748b",
    lineHeight: 1.3,
  },
  brandGst: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#334155",
    marginTop: 2,
  },
  docBadgeContainer: {
    width: "38%",
    alignItems: "flex-end",
  },
  docTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#167C80",
    letterSpacing: 0.8,
  },
  docRef: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#16324F",
    marginTop: 3,
  },
  statusBadge: {
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 8,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  metaGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  infoCardLeft: {
    width: "48%",
    backgroundColor: "#f8fafc",
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  infoCardRight: {
    width: "48%",
    backgroundColor: "#f8fafc",
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  cardHeading: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 5,
    paddingBottom: 3,
    borderBottomWidth: 0.8,
    borderBottomColor: "#cbd5e1",
  },
  entityName: {
    fontSize: 10.5,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 3,
  },
  cardText: {
    fontSize: 8.5,
    color: "#475569",
    lineHeight: 1.35,
  },
  keyValRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 2,
  },
  keyText: {
    fontSize: 8.5,
    color: "#64748b",
  },
  valText: {
    fontSize: 8.5,
    fontWeight: "bold",
    color: "#0f172a",
  },
  table: {
    width: "100%",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 5,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#16324F",
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    alignItems: "center",
  },
  tableRowAlt: {
    backgroundColor: "#f8fafc",
  },
  colSl: { width: "5%", textAlign: "center" },
  colItem: { width: "41%" },
  colQty: { width: "10%", textAlign: "center" },
  colPrice: { width: "14%", textAlign: "right" },
  colTax: { width: "15%", textAlign: "right" },
  colTotal: { width: "15%", textAlign: "right" },
  itemName: {
    fontSize: 8.5,
    fontWeight: "bold",
    color: "#0f172a",
  },
  itemSub: {
    fontSize: 7,
    color: "#64748b",
    marginTop: 1,
  },
  cellText: {
    fontSize: 8,
    color: "#334155",
  },
  cellTextBold: {
    fontSize: 8.5,
    fontWeight: "bold",
    color: "#0f172a",
  },
  summarySection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  paymentCard: {
    width: "50%",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 5,
    padding: 9,
  },
  paymentHeading: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#16324F",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  paymentDesc: {
    fontSize: 7.5,
    color: "#475569",
    lineHeight: 1.35,
    marginBottom: 6,
  },
  termsText: {
    fontSize: 7,
    color: "#64748b",
    lineHeight: 1.3,
  },
  totalsCard: {
    width: "46%",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 5,
    padding: 9,
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 2.5,
  },
  totalsBorder: {
    borderTopWidth: 1.5,
    borderTopColor: "#16324F",
    marginTop: 3,
    paddingTop: 4,
  },
  totalsTotalLabel: {
    fontSize: 9.5,
    fontWeight: "bold",
    color: "#16324F",
  },
  totalsTotalVal: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#16324F",
  },
  amountDueRow: {
    backgroundColor: "#f1f5f9",
    padding: 4,
    borderRadius: 4,
    marginTop: 3,
  },
  wordsBlock: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  wordsLabel: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: "#64748b",
    textTransform: "uppercase",
  },
  wordsText: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#0f172a",
    marginTop: 1,
  },
  signatorySection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 12,
    marginBottom: 20,
    paddingTop: 10,
  },
  signatoryLeft: {
    width: "55%",
  },
  signatoryRight: {
    width: "40%",
    alignItems: "flex-end",
  },
  signatoryFor: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#16324F",
    marginBottom: 26,
  },
  signatoryLine: {
    borderTopWidth: 0.8,
    borderTopColor: "#94a3b8",
    width: "100%",
    paddingTop: 3,
    alignItems: "flex-end",
  },
  signatoryTitle: {
    fontSize: 7.5,
    color: "#64748b",
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 36,
    right: 36,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 7.5,
    color: "#94a3b8",
  },
});
